[project]
name = "inference-arena"
version = "0.1.0"
authors = [{ name = "Fatih Buğra Akdoğan", email = "fatihb@firstbatch.xyz" }]
description = "Inference Arena Benchmark"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    # Database
    "pymongo>=4.6.0",
    "runpod>=1.7.0",
    "guidellm>=0.2.1",
    "lightning-sdk>=2025.8.28",
    "scaleway>=0.1.0",
    "paramiko>=3.4.0",
    "llm-optimizer",
]

[tool.uv.sources]
llm-optimizer = { git = "https://github.com/bentoml/llm-optimizer.git" }
